AllCops:
  Includes:
    - Rakefile
    - config.ru
    - app/**/*
  Excludes:
    - db/schema.rb
    - bin/**/*
    - vendor/bundle/**/*
    - app/views/**/*.erb
    - app/assets/**/*
    - app/**/*.swp
Metrics/LineLength:
    Max: 120
Metrics/MethodLength:
    Max: 15
Documentation:
  Enabled: false
