AllCops:
  Includes:
    - Rakefile
    - config.ru
    - app/**/*
  Excludes:
    - db/schema.rb
    - bin/**/*
    - vendor/bundle/**/*
    - app/views/**/*.erb
Metrics/LineLength:
    Max: 100
Documentation:
  Enabled: false
